spring:
  application:
    name: flow-no-code

  datasource:
    # banco existente apenas na JVM durante a execução
    url: jdbc:h2:mem:flownocode;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

logging:
  level:
    com.flownocode: DEBUG
    org.hibernate.SQL: INFO
