spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flownocode
    username: flownocode
    password: flownocode
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect